services:
  qemu1:
    container_name: win11
    image: dockurr/windows
    environment:
      #VERSION: "win11"
      DISK_SIZE: "32G"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      DISK2_SIZE: "4G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
     # - /media/1/iso/tiny11.iso:/custom.iso
     - /media:/shared
     - /home/rizwxn/docker/vm/windows/win11:/storage
     - /home/rizwxn/docker/vm/windows:/storage2
    ports:
      - 8301:8006
    networks:
      vlan:
        ipv4_address: 192.168.29.101
    stop_grace_period: 2m
    deploy:
      resources:
        limits:
          cpus: '3.00'  # Limit to 30% of a single CPU

networks:
  vlan:
    external: true
